name: flowmatch
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - contourpy=1.2.1=py39hdb19cb5_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - expat=2.6.4=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py39h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - icu=73.1=h6a678d5_0
  - importlib_resources=6.4.0=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libglib=2.78.4=hdc74915_0
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.9.2=py39h06a4308_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.4=h6a678d5_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - numpy=2.0.2=py39h5f9d8c6_0
  - numpy-base=2.0.2=py39hb5e798b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=24.2=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py39hcea889d_0
  - pip=25.0=py39h06a4308_0
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=6.7.1=py39h6a678d5_0
  - pyqt6-sip=13.9.1=py39h5eee18b_0
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py39h06a4308_0
  - sip=6.10.0=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py39h06a4308_0
  - tornado=6.4.2=py39h5eee18b_0
  - unicodedata2=15.1.0=py39h5eee18b_1
  - wheel=0.45.1=py39h06a4308_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.0
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - albucore==0.0.24
      - albumentations==2.0.6
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bleach==6.2.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - clean-fid==0.1.35
      - click==8.1.8
      - coloredlogs==15.0.1
      - comm==0.2.2
      - cython==3.1.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - diffusers==0.32.2
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - geomloss==0.2.6
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.30.1
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - insightface==0.7.3
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kaggle==1.7.4.5
      - kagglehub==0.3.13
      - keopscore==2.3
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.4.3
      - narwhals==1.42.1
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - opencv-python-headless==4.11.0.86
      - pandas==2.2.3
      - parso==0.8.4
      - pastel==0.2.1
      - pexpect==4.9.0
      - platformdirs==4.3.7
      - plotly==6.1.2
      - poethepoet==0.10.0
      - pot==0.9.5
      - prdc==0.2
      - prettytable==3.16.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==2.13.6
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pygments==2.19.1
      - pykeops==2.3
      - python-slugify==8.0.4
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentry-sdk==2.25.1
      - setproctitle==1.3.5
      - simsimd==6.2.1
      - smmap==5.0.2
      - stack-data==0.6.3
      - stringzilla==3.12.5
      - sympy==1.13.1
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==1.0.15
      - tokenizers==0.21.1
      - tomlkit==0.13.2
      - torch==2.6.0
      - torch-geometric==2.6.1
      - torchaudio==2.6.0
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.7.2
      - torchsde==0.2.6
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.50.3
      - triton==3.2.0
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.3.0
      - wandb==0.19.9
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - widgetsnbextension==4.0.14
      - yarl==1.20.0
prefix: /data/shahriar/miniconda3/envs/flowmatch
